name: lambda-depl

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && npm run build && zip -qq -r -j ./bundle.zip ./dist/*
      - name: deploy zip to aws lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: AKIAQLLCFR464RZMJRVF111
          aws_secret_access_key: V5iORE4lfSICeg28asR+l8MFnZlYnCN1JRChV1Ro
          aws_region: us-east-2
          function_name: function-test1
          zip_file: bundle.zip
